# GET http://localhost:3003/api/blogs/
# #

POST http://localhost:3000/api/blogs/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhY2tlciIsImlkIjoiNjJlMWJlNTY4Yjg5MjM0MmIzZTdhMDU0IiwiaWF0IjoxNjU5MTQ2MzAwLCJleHAiOjE2NTkxNDk5MDB9.zf0Ud9FqT-K5IpOPS6kgJFTTWHFgX2jtJR-Ltxpv0Do

{
    "title": "new funcionality",
    "author": "supa",
    "url": "www.simi666.wwr",
    "likes": "6",
    "userId": "62e1be568b892342b3e7a054"

}

###
POST http://localhost:3000/api/login/
content-type: application/json


{
    "username": "hacker",
    "password": "indacity"
}